name: Deploy Backend to Heroku (Basic)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Heroku
        uses: behe/heroku-build@v1
        with:
          app-name: ${{ secrets.HEROKU_APP_NAME }}
          api-key: ${{ secrets.HEROKU_API_KEY }}
          process-types: '{"web": "cd backend && gunicorn app:app"}'
          path: "backend" 