name: Deploy Backend to Heroku (Container)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy-container.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Heroku Container registry
        uses: docker/login-action@v2
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ secrets.HEROKU_API_KEY }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          curl -X PATCH https://api.heroku.com/apps/${{ secrets.HEROKU_APP_NAME }}/formation \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
            -H "Authorization: Bearer ${HEROKU_API_KEY}" \
            -d '{"updates":[{"type":"web","docker_image":"$(curl -n -X GET https://api.heroku.com/apps/${{ secrets.HEROKU_APP_NAME }}/formation \
                  -H "Accept: application/vnd.heroku+json; version=3" \
                  -H "Authorization: Bearer ${HEROKU_API_KEY}" | jq ".[0].id")"}]}' 