name: Deploy Backend to Heroku (Container)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to Heroku
        uses: devigned/deploy-to-heroku-action@v1.1.2
        with:
          api-key: ${{ secrets.HEROKU_API_KEY }}
          app-name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile-path: backend/Dockerfile
          app-dir: backend 